package com.github.ivan.kopylove.persistence.hibernate;

import com.github.ivan.kopylove.sandbox.persistence.entities.ParentEntity;
import com.github.ivan.kopylove.sandbox.persistence.util.HibernateSessionFactory;
import org.hibernate.Session;
import org.hibernate.proxy.HibernateProxy;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * this example demonsrates that
 * 1. entity var is buildEntityManagerFactory pure object
 */
class HibernateLoadvsGetExampleTest
{

    @BeforeAll
    public static void populate()
    {
        ParentEntity parentEntity = new ParentEntity();
        parentEntity.setId(0);
        parentEntity.setName("some parent name");

        Session session = HibernateSessionFactory.openSession();
        session.getTransaction()
               .begin();
        session.save(parentEntity);
        session.getTransaction()
               .commit();
    }

    /**
     * session.get() hits the database immediately
     */
    @Test
    void get()
    {
        Session session = HibernateSessionFactory.openSession();
        session.getTransaction()
               .begin();
        ParentEntity entity = session.get(ParentEntity.class, 0); //pure java object
        session.getTransaction()
               .commit();

        assertFalse(entity instanceof HibernateProxy);
        assertFalse(entity.getClass()
                          .toString()
                          .contains("$HibernateProxy$"));
        session.close();
    }

    /**
     * ParentEntity is proxy
     */
    @Test
    void load()
    {
        Session session = HibernateSessionFactory.openSession();
        session.getTransaction()
               .begin();
        ParentEntity parentEntity = session.load(ParentEntity.class, 9999999); //proxy object generated by hibernate
        session.getTransaction()
               .commit();

        assertInstanceOf(HibernateProxy.class, parentEntity);
        assertTrue(parentEntity.getClass()
                               .toString()
                               .contains("$HibernateProxy$"));

        session.close();
    }
}
